name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  release:
    name: Release x64
    runs-on: windows

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        shell: cmd
        run: >
          "E:\VisualStudioBuildTools\MSBuild\Current\Bin\amd64\MSBuild.exe" Sunrise.sln /m
          /p:Configuration=Release
          /p:Platform=x64
          /p:PreferredToolArchitecture=x64
          /verbosity:minimal

      - name: Get short commit hash
        shell: cmd
        run: |
          for /f %%i in ('git rev-parse --short HEAD') do set "SHORT_SHA=%%i"
          echo SHORT_SHA=%SHORT_SHA%>>%GITHUB_ENV%

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Sunrise-${{ gitea.ref_name }}-${{ env.SHORT_SHA }}-Release-x64
          path: |
            build/x64/Release/steam_api64.dll
            build/x64/Release/steam_api64.pdb
          if-no-files-found: error